# Generated by Django 5.0.2 on 2024-10-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_delete_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='name',
        ),
    ]
