# Generated by Django 5.0.2 on 2024-10-12 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='deposit_his',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
                ('proof', models.FileField(upload_to='proof/')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('paymentm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.paymentmethod')),
            ],
        ),
    ]
