# Generated by Django 5.0.2 on 2024-10-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_deposit_his'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_his',
            name='address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
