# Generated by Django 5.0.2 on 2024-11-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_assetbuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='house/other_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('main_picture', models.FileField(upload_to='house/main_pictures/')),
                ('other_pictures', models.ManyToManyField(related_name='houses', to='userapp.housepicture')),
            ],
        ),
    ]
