# Generated by Django 5.0.2 on 2024-11-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_house_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(default='mmml', max_length=10000),
        ),
    ]
