# Generated by Django 5.0.2 on 2024-11-13 20:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_house_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='housebuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(default='Bought', max_length=100)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
