# Generated by Django 5.0.2 on 2024-11-17 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_housebuy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePurchaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=100)),
                ('ssn', models.CharField(max_length=20)),
                ('current_address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_statements', models.FileField(upload_to='bank_statements/')),
                ('credit_score', models.IntegerField()),
                ('employer_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=100)),
                ('employment_duration_years', models.IntegerField()),
                ('property_address', models.CharField(max_length=255)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='housebuy',
            name='HousePurchaseInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.housepurchaseinfo'),
            preserve_default=False,
        ),
    ]
