# Generated by Django 5.0.2 on 2024-11-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_housepurchaseinfo_housebuy_housepurchaseinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseforrentPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='houseforrent/rentother_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Houseforrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=1000)),
                ('description', models.TextField(default='mmml', max_length=10000)),
                ('features', models.TextField(max_length=10000)),
                ('main_picture', models.FileField(upload_to='houseforrent/main_pictures/')),
                ('rentother_pictures', models.ManyToManyField(related_name='houses', to='userapp.houseforrentpictures')),
            ],
        ),
    ]
