# Generated by Django 5.0.2 on 2024-11-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_houseforrentpictures_houseforrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_rental_address', models.CharField(max_length=255)),
                ('landlord_name', models.CharField(max_length=100)),
                ('landlord_contact', models.CharField(max_length=50)),
                ('reason_for_moving', models.TextField()),
                ('job_title', models.CharField(max_length=100)),
                ('employer_name', models.CharField(max_length=100)),
                ('employer_contact', models.CharField(max_length=50)),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consent', models.BooleanField(default=False)),
            ],
        ),
    ]
