# Generated by Django 5.0.2 on 2024-11-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_withdraw_his'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw_his',
            name='proof',
        ),
    ]
