# Generated by Django 5.0.2 on 2024-11-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Share', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
            ],
        ),
    ]
