# Generated by Django 5.0.2 on 2024-11-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='update_interval',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='shares',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shares',
            name='value',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=12),
        ),
    ]
