# Generated by Django 5.0.2 on 2024-11-29 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_shares_update_interval_alter_shares_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=100.0, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('update_interval', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
