# Generated by Django 5.0.2 on 2024-11-29 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_user_shares'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='img',
            field=models.ImageField(default=1, upload_to='sharesimg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_shares',
            name='shares',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userapp.shares'),
            preserve_default=False,
        ),
    ]
