# Generated by Django 5.0.2 on 2024-11-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0028_user_shares_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_shares',
            name='add_up',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user_shares',
            name='end',
            field=models.IntegerField(default=20),
        ),
    ]
