# Generated by Django 5.0.2 on 2024-11-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0029_user_shares_add_up_user_shares_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_shares',
            name='add_up',
        ),
    ]
