# Generated by Django 5.0.2 on 2024-11-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0030_remove_user_shares_add_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_shares',
            old_name='end',
            new_name='end_interval',
        ),
    ]
