# Generated by Django 5.0.2 on 2024-11-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0031_rename_end_user_shares_end_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_shares',
            name='amount',
            field=models.IntegerField(default=600),
        ),
    ]
