# Generated by Django 5.0.2 on 2024-11-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0033_user_shares_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shares',
            name='end_interval',
            field=models.IntegerField(default=20),
        ),
    ]
