# Generated by Django 5.0.2 on 2024-11-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0034_shares_end_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_shares',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
