# Generated by Django 5.0.2 on 2024-12-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0036_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='location_link',
            field=models.URLField(default='https://googlemap.com'),
        ),
    ]
