# Generated by Django 5.0.2 on 2024-12-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0037_house_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepicture',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
