# Generated by Django 5.0.2 on 2024-12-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0039_notification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='location_link',
            field=models.URLField(default='https://googlemap.com', max_length=5000),
        ),
    ]
