# Generated by Django 5.0.2 on 2024-12-03 22:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0040_alter_house_location_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage_increase', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage_decrease', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('increase_time', models.TimeField()),
                ('decrease_time', models.TimeField()),
                ('last_update', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
