# Generated by Django 5.0.2 on 2024-12-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0041_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='image',
            field=models.FileField(default=1, upload_to='stocks/'),
            preserve_default=False,
        ),
    ]
