# Generated by Django 5.0.2 on 2024-12-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0042_stock_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='last_update',
            new_name='ldate',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='decrease_time',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='increase_time',
        ),
        migrations.AddField(
            model_name='stock',
            name='decrease_interval',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='increase_interval',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='stock',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
