# Generated by Django 5.0.2 on 2024-12-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0046_alter_stock_user_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradeplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='tradeimg')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('update_interval', models.PositiveIntegerField()),
                ('end_time', models.PositiveIntegerField()),
            ],
        ),
    ]
