# Generated by Django 5.0.2 on 2024-12-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0048_remove_tradeplan_balance_tradeplan_max_tradeplan_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeplan',
            name='period',
            field=models.CharField(default='1 Month', max_length=100),
        ),
    ]
