# Generated by Django 5.0.2 on 2024-12-13 16:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0049_tradeplan_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('period', models.CharField(default='1 Month', max_length=100)),
                ('update_interval', models.PositiveIntegerField()),
                ('end_time', models.PositiveIntegerField()),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tradeplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.tradeplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
