# Generated by Django 5.0.2 on 2024-12-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0050_user_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_trades',
            name='value',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=12),
        ),
    ]
