# Generated by Django 5.0.2 on 2024-12-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0052_remove_user_trades_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_trades',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
