# Generated by Django 5.0.2 on 2024-12-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0053_user_trades_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_trades',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
