# Generated by Django 5.0.2 on 2024-12-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0054_user_trades_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='stocks_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('image', models.FileField(upload_to='stocc/')),
                ('description', models.TextField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_active', models.BooleanField(default=True)),
                ('profit_start_seconds', models.IntegerField(blank=True, null=True)),
                ('loss_start_seconds', models.IntegerField(blank=True, null=True)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('loss_percentage', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
            ],
        ),
    ]
