# Generated by Django 5.0.2 on 2024-12-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0056_compstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='compstocks',
            name='last_updated',
            field=models.IntegerField(default=0),
        ),
    ]
